#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_follows_focus true
bspc config focus_follows_pointer true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a firefox desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Yad state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


# Border
bspc config focused_border_color        "#6c71c4"
bspc config normal_border_color         "#073642"
bspc config active_border_color         "#073642"

#
# Autostart
#

# Set display from arandr saved script
# sh ~/.screenlayout/monitor.sh &

# Bar
# ~/.config/polybar/launch.sh &

# Notifications
# /usr/bin/dunst &

# Picom
# picom -b &

# Cursor
xsetroot -cursor_name left_ptr &

# Automount disks
# udiskie &

# Repeat speed
# xset r rate 200 30

# Low battery notifier
low-bat-notifier &

# Set wallpaper
~/.fehbg

# Start a terminal on launch
alacritty &
